### ISSUE TITLE
Plugin doesn't work with the CDN version of UnoCSS

### ISSUE THREAD

**Issue by igormichalak** [re-ovo/unocss-intellij#21]
![Screenshot from 2023-09-03 13-08-34](https://github.com/re-ovo/unocss-intellij/assets/98187995/5ef73923-0428-4e46-931e-8427a345bee3)

**Comment by re-ovo** [comment]
This is intentional, I don't intend to support cdn import, it seems contradictory: not use some powerful front-end framework, but use unocss, I don't see the point of this. I know that using a framework like alpinejs can make development "lightweight", but I can't see more benefits, it is not the future. 
Also, the VSCode plugin also does not support this.
